name: blinkist
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    




 
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  carousel_pro: ^0.0.13
  transformer_page_view:


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
   - images/ic_launcher.png
   - images/flower.jpg
   - images/flower1.jpg
   - images/flower2.jpg
   - images/sea.jpg
   - images/flower4.jpg
   - images/ic_launcher2.png
   - images/book.jpg
   - images/book1.jpg
   - images/alarm.jpg
   - images/ph1.jpg
   - images/ph2.jpg
   - images/ph3.jpg
   - images/ph4.jpg
   - images/ph5.jpg
   - images/ph6.jpg
   - images/ph7.jpg
   - images/ph8.jpg
   - images/ph9.jpg
   - images/ph10.jpg
   - images/ph11.jpg
   - images/ph12.jpg
   - images/ph13.jpg
   - images/ph14.jpg
   - images/ph15.jpg
   - images/ph16.jpg
   - images/ph17.jpg
   - images/ph18.jpg
   - images/ph19.jpg
   - images/ph20.jpg
   - images/ph21.jpg
   - images/ph22.jpg
   - images/ph23.jpg
   - images/ph24.jpg
   - images/ph25.jpg
   - images/ph26.jpg
   - images/ph27.jpg
   - images/ph28.jpg
   - images/ph29.jpg
   - images/ph30.jpg
   - images/ph31.jpg
   - images/ph32.jpg
   - images/ph33.jpg
   - images/ph34.jpg
   - images/ph35.jpg
   - images/ph36.jpg
   - images/ph37.jpg
   - images/ph38.jpg
   - images/ph39.jpg
   - images/ph41.jpg
   - images/ic_launch_logo.png
  
   











  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Raleway
       fonts:
         - asset: fonts/Raleway-Regular.ttf
         - asset: fonts/Raleway-Black.ttf
         - asset: fonts/Raleway-SemiBold.ttf
         - asset: fonts/Raleway-Italic.ttf
         - asset: fonts/Raleway-LightItalic.ttf
           weight: 300
           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
